apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-dotnet-basic-qyhmmhpq
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-dotnet-basic-qyhmmhpq:dd06192f22e1aa13405325b3fecc6291bfe9b83f@sha256:622be0cc60694b721f36868aac5d2a3f329d65086f8e15b52977257c316504c3
          name: container-image
